import {
  UserProfile,
  FoodAnalysisResult,
  MenuAnalysis,
  WeeklyPlan,
  FoodProfileComparison,
  ClarificationQuestion,
  DishReformulation,
} from './types';

export const CURRENT_USER_PROFILE: UserProfile = {
  id: 'clara-m',
  name: 'Clara M.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  conditions: ['Type 2 Diabetes', 'Hypertension', 'Histamine Intolerance'],
  allergies: ['Tree Nut Allergy', 'Shellfish'],
  dietType: 'Botanical Clinical Low-Histamine & Glycemic Guard',
  goals: ['Blood Sugar Stability (GL ≤ 10)', 'Low Sodium (<400mg/meal)', 'Zero Allergen Cross-Traces'],
  doctorNoteUploaded: true,
  doctorNoteFileName: 'dr_endocrinology_eval_2026.pdf',
};

export const COMPARISON_PROFILES: UserProfile[] = [
  CURRENT_USER_PROFILE,
  {
    id: 'marcus-k',
    name: 'Marcus K.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    conditions: ['Celiac Disease', 'Fatty Liver'],
    allergies: ['Gluten', 'Dairy'],
    dietType: 'Strict Keto & Gluten-Free',
    goals: ['Ketosis Maintenance', 'Zero Gluten Cross-Contamination'],
    doctorNoteUploaded: false,
  },
  {
    id: 'elena-r',
    name: 'Elena R.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
    conditions: ['CKD Stage 2', 'IBS'],
    allergies: ['Soy', 'Peanuts'],
    dietType: 'Low FODMAP & Renal Guard',
    goals: ['Potassium Balance', 'Zero High-FODMAP Polyols'],
    doctorNoteUploaded: true,
    doctorNoteFileName: 'nephrology_diet_plan.pdf',
  },
];

export const MOCK_CLARIFICATION_QUESTION: ClarificationQuestion = {
  id: 'clarify-pad-thai',
  foodName: 'Artisanal Tamarind Pad Thai',
  question: 'Did the kitchen prepare this with fermented fish sauce or coconut aminos?',
  subtext: 'Fermented fish sauce triggers a strong histamine response for Clara’s profile, whereas organic coconut aminos makes this dish 100% safe.',
  options: [
    {
      id: 'opt-fish-sauce',
      label: 'Fermented Fish Sauce (Traditional Wok)',
      details: 'Triggers Histamine Intolerance risk + high sodium content',
      targetResultId: 'pad-thai-classic',
    },
    {
      id: 'opt-coconut-aminos',
      label: 'Organic Coconut Aminos & Lime',
      details: 'Eliminates histamine trigger, reduces sodium by 65%',
      targetResultId: 'pad-thai-reformulated-safe',
    },
    {
      id: 'opt-unknown',
      label: 'Not Sure / Standard Kitchen Recipe',
      details: 'Evaluates conservatively based on traditional ingredients',
      targetResultId: 'pad-thai-classic',
    },
  ],
};

export const MOCK_REFORMULATION_PAD_THAI: DishReformulation = {
  id: 'pad-thai-reformulated',
  foodName: 'Artisanal Tamarind Pad Thai',
  originalDish: {
    name: 'Traditional Tamarind Pad Thai',
    verdict: 'risk',
    explanation: 'High histamine load from fermented anchovy fish sauce, high sodium (890mg), and crushed peanut allergy trigger.',
    ingredients: ['Rice Noodles', 'Tamarind Paste', 'Fermented Fish Sauce', 'Crushed Peanuts', 'Palm Sugar', 'Egg', 'Bean Sprouts'],
    nutritionSummary: 'Glycemic Load: 24 (High) | Sodium: 890mg | Histamine Score: High',
  },
  modifiedDish: {
    name: 'Swaahara Compatible Botanical Pad Thai',
    verdict: 'safe',
    explanation: 'Substituted fermented fish sauce with organic coconut aminos, replaced crushed peanuts with toasted pumpkin seeds, and used monk fruit extract.',
    ingredients: ['Kelp & Rice Noodle Blend', 'Fresh Tamarind Puree', 'Organic Coconut Aminos', 'Toasted Pumpkin Seeds', 'Monk Fruit Extract', 'Organic Pasture Egg', 'Bean Sprouts'],
    nutritionSummary: 'Glycemic Load: 7 (Low) | Sodium: 260mg | Histamine Score: Minimal',
    changesMade: [
      'Substituted Fermented Fish Sauce with Organic Coconut Aminos (Eliminates Histamine Risk)',
      'Replaced Crushed Peanuts with Toasted Pumpkin Seeds (Eliminates Allergen Risk)',
      'Replaced Palm Sugar with Monk Fruit Extract (Stabilizes Blood Sugar & Glycemic Index)',
      'Reduced Sodium by 70% to 260mg per serving (Protects Blood Pressure)',
    ],
  },
};

export const MOCK_FOOD_RESULTS: Record<string, FoodAnalysisResult> = {
  'pad-thai-classic': {
    id: 'pad-thai-classic',
    foodName: 'Artisanal Tamarind Pad Thai',
    category: 'Thai Cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&q=80&w=800',
    verdict: 'risk',
    verdictTitle: 'High Histamine & Sodium Risk',
    verdictSummary: 'Contains fermented anchovy fish sauce (histamine spike hazard), crushed peanuts (tree nut / peanut cross-contamination risk), and 890mg sodium (exceeds hypertension threshold).',
    confirmedRisks: [
      {
        id: 'r1',
        title: 'Fermented Anchovy Fish Sauce',
        description: 'Fermentation produces biogenic amines that cause immediate histamine flare-ups and flushing.',
        severity: 'high',
        triggeredBy: 'Fermented Anchovy Extract',
        affectedConditionOrAllergy: 'Histamine Intolerance',
      },
      {
        id: 'r2',
        title: 'Crushed Peanut Garnish',
        description: 'Direct peanut contact poses severe allergen trigger for your recorded nut sensitivity.',
        severity: 'high',
        triggeredBy: 'Whole & Crushed Peanuts',
        affectedConditionOrAllergy: 'Tree Nut / Peanut Allergy',
      },
      {
        id: 'r3',
        title: 'High Sodium Wok Glaze (890mg)',
        description: 'Exceeds your target threshold of 400mg per meal for blood pressure management.',
        severity: 'medium',
        triggeredBy: 'Refined Salt & Soy Extract',
        affectedConditionOrAllergy: 'Hypertension',
      },
    ],
    potentialRisks: [
      {
        id: 'pr1',
        title: 'Palm Sugar Reduction Syrup',
        description: 'Fast-digesting simple sugars in traditional tamarind glaze may cause a glycemic surge.',
        severity: 'medium',
        triggeredBy: 'Concentrated Palm Sugar',
        affectedConditionOrAllergy: 'Type 2 Diabetes',
      },
    ],
    unknowns: [
      {
        id: 'u1',
        title: 'Wok Cooking Oil Origin',
        description: 'Kitchen may reuse wok oil previously used for shellfish tempura or peanut appetizers.',
        reason: 'Unspecified restaurant frying practices',
      },
    ],
    nutritionalHighlights: [
      { label: 'Glycemic Load', value: '24 (High)' },
      { label: 'Sodium per Portion', value: '890 mg' },
      { label: 'Histamine Index', value: 'Level 4 / 5' },
      { label: 'Net Carbs', value: '58 g' },
    ],
    reformulation: MOCK_REFORMULATION_PAD_THAI,
  },
  'pad-thai-reformulated-safe': {
    id: 'pad-thai-reformulated-safe',
    foodName: 'Swaahara Compatible Botanical Pad Thai',
    category: 'Thai Cuisine (Modified)',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&q=80&w=800',
    verdict: 'safe',
    verdictTitle: '100% Compatible & Histamine-Safe',
    verdictSummary: 'Prepared with organic coconut aminos, monk fruit sweetener, and pumpkin seed garnish. Fully aligned with Clara’s metabolic & allergen profile.',
    confirmedRisks: [],
    potentialRisks: [],
    unknowns: [
      {
        id: 'u-safe-1',
        title: 'Fresh Lime Storage Duration',
        description: 'Slight increase in citrus amines if stored over 48 hours, though typically benign.',
        reason: 'Kitchen prep timing',
      },
    ],
    nutritionalHighlights: [
      { label: 'Glycemic Load', value: '7 (Low)' },
      { label: 'Sodium per Portion', value: '260 mg' },
      { label: 'Histamine Index', value: 'Level 1 / 5' },
      { label: 'Net Carbs', value: '18 g' },
    ],
    reformulation: MOCK_REFORMULATION_PAD_THAI,
  },
  'wild-salmon-bowl': {
    id: 'wild-salmon-bowl',
    foodName: 'Steamed Wild Salmon & Asparagus Bowl',
    category: 'Clinical Farm-to-Table',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=800',
    verdict: 'safe',
    verdictTitle: 'Optimal Botanical Alignment',
    verdictSummary: 'Zero allergen triggers detected. High in anti-inflammatory Omega-3s, low glycemic impact (GL 4), and minimal sodium (180mg).',
    confirmedRisks: [],
    potentialRisks: [],
    unknowns: [
      {
        id: 'u-salmon-1',
        title: 'Herb Infusion Dressing Origin',
        description: 'Dressing confirmed olive oil & dill based with zero hidden vinegar or aged additives.',
        reason: 'Supplier verification clean',
      },
    ],
    nutritionalHighlights: [
      { label: 'Glycemic Load', value: '4 (Optimal)' },
      { label: 'Sodium per Portion', value: '180 mg' },
      { label: 'Histamine Index', value: 'Level 0 / 5' },
      { label: 'Omega-3 Fatty Acids', value: '2,400 mg' },
    ],
  },
  'wild-mushroom-risotto': {
    id: 'wild-mushroom-risotto',
    foodName: 'Truffle & Wild Mushroom Risotto',
    category: 'Italian Cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&q=80&w=800',
    verdict: 'caution',
    verdictTitle: 'Requires Portion Moderation',
    verdictSummary: 'Aged parmesan contains moderate tyramine and histamine. Arborio rice base has a medium glycemic index (GL 16); half portion is recommended.',
    confirmedRisks: [
      {
        id: 'r-risotto-1',
        title: '24-Month Aged Parmesan Shavings',
        description: 'Aged cheeses contain concentrated histamines that can induce mild headache or congestion.',
        severity: 'medium',
        triggeredBy: 'Aged Dairy Proteins',
        affectedConditionOrAllergy: 'Histamine Intolerance',
      },
    ],
    potentialRisks: [
      {
        id: 'pr-risotto-1',
        title: 'Arborio White Rice Starch',
        description: 'Rapidly absorbed starchy rice can cause postprandial blood glucose elevation if consumed in full portion.',
        severity: 'medium',
        triggeredBy: 'High Glycemic Starch',
        affectedConditionOrAllergy: 'Type 2 Diabetes',
      },
    ],
    unknowns: [
      {
        id: 'u-risotto-1',
        title: 'Vegetable Broth Base',
        description: 'Check if broth uses commercial yeast extract or hydrolyzed protein.',
        reason: 'Commercial seasoning blend variance',
      },
    ],
    nutritionalHighlights: [
      { label: 'Glycemic Load', value: '16 (Moderate)' },
      { label: 'Sodium per Portion', value: '380 mg' },
      { label: 'Histamine Index', value: 'Level 3 / 5' },
      { label: 'Net Carbs', value: '42 g' },
    ],
  },
};

export const MOCK_MENU_ANALYSIS: MenuAnalysis = {
  id: 'botanica-bistro',
  restaurantName: 'Botanica Green Bistro',
  cuisine: 'Clinical & Farm-to-Table',
  dishes: [
    {
      id: 'dish-1',
      dishName: 'Steamed Wild King Salmon with Asparagus',
      description: 'Poached wild Alaska salmon served over steamed green asparagus and lemon-herb drizzle.',
      price: '$28.00',
      verdict: 'safe',
      oneLineReason: 'Zero allergen triggers, low glycemic index (GL 4), and low sodium (180mg).',
      matchedConditions: ['Type 2 Diabetes Safe', 'Histamine Level 0', 'Low Sodium'],
      category: 'Main Course',
    },
    {
      id: 'dish-2',
      dishName: 'Pasture Chicken Breast & Baby Spinach Salad',
      description: 'Fresh non-aged chicken breast with baby spinach, cucumber, pumpkin seeds, and extra virgin olive oil.',
      price: '$22.00',
      verdict: 'safe',
      oneLineReason: 'Fresh un-aged poultry and pumpkin seeds eliminate histamine & nut allergen risks.',
      matchedConditions: ['Tree Nut Free', 'Histamine Level 0', 'Glycemic Guard'],
      category: 'Salads & Greens',
    },
    {
      id: 'dish-3',
      dishName: 'Zucchini Noodle Basil Pesto',
      description: 'Spiralized fresh zucchini tossed with house nut-free pumpkin seed basil pesto and cherry tomatoes.',
      price: '$19.00',
      verdict: 'safe',
      oneLineReason: 'Nut-free seed pesto variant, zero glycemic carbohydrate spike.',
      matchedConditions: ['Nut Free', 'Keto / Low GL', 'Sodium Guard'],
      category: 'Pasta & Noodles',
    },
    {
      id: 'dish-4',
      dishName: 'Pan-Seared Halibut with Dill Butter Sauce',
      description: 'Wild halibut fillet pan-seared with cultured grass-fed butter, fresh dill, and capers.',
      price: '$31.00',
      verdict: 'caution',
      oneLineReason: 'Butter & capers add moderate sodium and trace histamines; request olive oil swap.',
      matchedConditions: ['Request Oil Swap', 'Moderate Histamine'],
      category: 'Main Course',
    },
    {
      id: 'dish-5',
      dishName: 'Truffle & Wild Mushroom Arborio Risotto',
      description: 'Creamy Arborio rice with porcini mushrooms, truffle essence, and aged parmesan cheese.',
      price: '$26.00',
      verdict: 'caution',
      oneLineReason: 'Aged parmesan introduces histamines; white arborio rice requires half-portion control for GL.',
      matchedConditions: ['Glycemic Watch', 'Aged Cheese Trace'],
      category: 'Main Course',
    },
    {
      id: 'dish-6',
      dishName: 'Aged Tenderloin with Red Wine Reduction',
      description: '28-day dry-aged beef fillet served with fermented red wine glaze and truffle potato puree.',
      price: '$42.00',
      verdict: 'risk',
      oneLineReason: 'Dry-aged beef & red wine reduction trigger severe histamine reactions & blood pressure spike.',
      matchedConditions: ['High Histamine Warning', 'High Sodium (920mg)'],
      category: 'Main Course',
    },
    {
      id: 'dish-7',
      dishName: 'Thai Peanut Wok Noodle Bowl with Crispy Tofu',
      description: 'Wok-fried rice noodles in crushed peanut coconut sauce with fermented soy tofu and chili crisp.',
      price: '$21.00',
      verdict: 'risk',
      oneLineReason: 'Contains heavy crushed peanut sauce (allergen hazard) and fermented soy (histamine trigger).',
      matchedConditions: ['Tree Nut / Peanut Trigger', 'Histamine Hazard'],
      category: 'Asian Wok',
    },
  ],
};

export const MOCK_WEEKLY_PLAN: WeeklyPlan = {
  days: [
    {
      day: 'Monday',
      dateLabel: 'Oct 12',
      meals: [
        {
          id: 'm1',
          mealType: 'Breakfast',
          recipeTitle: 'Chia Seed & Coconut Milk Pudding with Fresh Blueberries',
          prepTime: '10 mins',
          verdict: 'safe',
          highlights: ['Glycemic Load: 3', 'Zero Histamine', 'Rich in Fiber'],
          recipe: {
            id: 'rec-1',
            title: 'Chia Seed & Coconut Milk Pudding',
            servings: 2,
            prepTime: '10 mins',
            ingredients: ['1/4 cup Organic Chia Seeds', '1 cup Unsweetened Coconut Milk', '1/2 cup Fresh Blueberries', '1/4 tsp Pure Vanilla Extract', 'Monk fruit sweetener to taste'],
            instructions: [
              'Whisk chia seeds, coconut milk, vanilla, and sweetener together in a glass jar.',
              'Refrigerate for at least 4 hours or overnight until thickened.',
              'Top with fresh blueberries before serving.',
            ],
            compatibilityNotes: '100% compatible with Clara’s profile. Zero nut allergens, extremely low glycemic impact, and no histamine fermentation.',
          },
        },
        {
          id: 'm2',
          mealType: 'Lunch',
          recipeTitle: 'Steamed Salmon & Asparagus Bowl with Olive Oil Dressing',
          prepTime: '20 mins',
          verdict: 'safe',
          highlights: ['Omega-3 Boost', 'Sodium: 180mg', 'GL: 4'],
          recipe: {
            id: 'rec-2',
            title: 'Steamed Salmon & Asparagus Bowl',
            servings: 1,
            prepTime: '20 mins',
            ingredients: ['6 oz Wild Alaskan Salmon Fillet', '1 cup Fresh Asparagus spears', '1 tbsp Extra Virgin Olive Oil', 'Fresh Lemon Juice & Dill', 'Pinch of Himalayan Pink Salt'],
            instructions: [
              'Steam salmon fillet and asparagus spears over simmering water for 8-10 minutes.',
              'Drizzle with extra virgin olive oil and squeeze fresh lemon juice.',
              'Garnish with fresh dill and serve warm.',
            ],
            compatibilityNotes: 'Non-aged fresh fish provides anti-inflammatory EPA/DHA without histamine buildup. Asparagus supports kidney filtration.',
          },
        },
        {
          id: 'm3',
          mealType: 'Dinner',
          recipeTitle: 'Botanical Zucchini Noodle Pesto with Toasted Pumpkin Seeds',
          prepTime: '15 mins',
          verdict: 'safe',
          highlights: ['Nut-Free Pesto', 'GL: 2', 'Histamine-Free'],
          recipe: {
            id: 'rec-3',
            title: 'Botanical Zucchini Noodle Pesto',
            servings: 2,
            prepTime: '15 mins',
            ingredients: ['3 medium Zucchinis, spiralized', '1 cup Fresh Basil Leaves', '1/3 cup Toasted Pumpkin Seeds', '1/3 cup Extra Virgin Olive Oil', '1 clove Garlic', 'Sea salt to taste'],
            instructions: [
              'Blend basil, pumpkin seeds, garlic, olive oil, and sea salt in a food processor until smooth pesto forms.',
              'Sauté zucchini noodles in a pan for 2 minutes until tender-crisp.',
              'Toss noodles with pumpkin seed pesto and serve immediately.',
            ],
            compatibilityNotes: 'Replaces pine nuts with toasted pumpkin seeds for total nut-allergy safety. Zucchini replaces starchy pasta for diabetes stability.',
          },
        },
      ],
    },
    {
      day: 'Tuesday',
      dateLabel: 'Oct 13',
      meals: [
        {
          id: 'm4',
          mealType: 'Breakfast',
          recipeTitle: 'Pasture Egg Omelet with Fresh Spinach & Zucchini Shavings',
          prepTime: '12 mins',
          verdict: 'safe',
          highlights: ['High Protein', 'GL: 1', 'Zero Dairy'],
          recipe: {
            id: 'rec-4',
            title: 'Pasture Egg & Baby Spinach Omelet',
            servings: 1,
            prepTime: '12 mins',
            ingredients: ['3 Organic Pasture Eggs', '1 cup Baby Spinach', '1/2 Zucchini, thinly sliced', '1 tbsp Extra Virgin Olive Oil', 'Fresh Herbs (Parsley, Chives)'],
            instructions: [
              'Whisk eggs with a tablespoon of water and chopped fresh chives.',
              'Heat olive oil in a skillet and sauté zucchini and spinach for 1 minute.',
              'Pour egg mixture over vegetables and cook until set.',
            ],
            compatibilityNotes: 'Freshly laid un-aged eggs provide complete protein without histamine or carbohydrate spikes.',
          },
        },
        {
          id: 'm5',
          mealType: 'Lunch',
          recipeTitle: 'Pasture Chicken Breast & Cucumbers in Seed Dressing',
          prepTime: '15 mins',
          verdict: 'safe',
          highlights: ['Low Sodium', 'Zero Allergen', 'GL: 3'],
          recipe: {
            id: 'rec-5',
            title: 'Pasture Chicken & Cucumber Salad',
            servings: 1,
            prepTime: '15 mins',
            ingredients: ['5 oz Fresh Poached Chicken Breast, sliced', '1.5 cups Crisp Cucumber slices', '2 tbsp Tahini or Sunflower Seed Butter dressing', 'Lemon zest & herbs'],
            instructions: [
              'Combine sliced cucumber and poached chicken in a salad bowl.',
              'Dress with sunflower seed dressing and lemon zest.',
            ],
            compatibilityNotes: 'Clean, unfermented lunch option ensuring blood pressure and histamine safety.',
          },
        },
        {
          id: 'm6',
          mealType: 'Dinner',
          recipeTitle: 'Pan-Seared Cod Fillet with Roasted Cauliflower Steaks',
          prepTime: '25 mins',
          verdict: 'safe',
          highlights: ['Sodium: 210mg', 'GL: 4', 'Kidney Safe'],
          recipe: {
            id: 'rec-6',
            title: 'Pan-Seared Cod & Cauliflower Steaks',
            servings: 2,
            prepTime: '25 mins',
            ingredients: ['2 Wild Cod Fillets (6 oz each)', '1 head Cauliflower, cut into thick steaks', '2 tbsp Avocado Oil', 'Fresh Thyme & Rosemary'],
            instructions: [
              'Roast cauliflower steaks with avocado oil and herbs at 400°F (200°C) for 20 minutes.',
              'Pan-sear cod fillets in a skillet for 3-4 minutes per side.',
              'Serve cod over roasted cauliflower steaks.',
            ],
            compatibilityNotes: 'Cod is cooked immediately after catch freezing to prevent histamine accumulation.',
          },
        },
      ],
    },
    {
      day: 'Wednesday',
      dateLabel: 'Oct 14',
      meals: [
        {
          id: 'm7',
          mealType: 'Breakfast',
          recipeTitle: 'Warm Quinoa Porridge with Baked Apple & Cinnamon',
          prepTime: '15 mins',
          verdict: 'safe',
          highlights: ['GL: 8', 'Heart Healthy', 'Low Sodium'],
          recipe: {
            id: 'rec-7',
            title: 'Quinoa Porridge with Cinnamon Apple',
            servings: 2,
            prepTime: '15 mins',
            ingredients: ['1 cup Cooked Quinoa', '1 cup Almond Milk (Nut-Free Seed Milk alternative)', '1 Green Apple, diced', '1/2 tsp Ceylon Cinnamon'],
            instructions: [
              'Simmer cooked quinoa with seed milk and diced green apple for 8 minutes.',
              'Stir in Ceylon cinnamon and serve warm.',
            ],
            compatibilityNotes: 'Ceylon cinnamon helps enhance insulin sensitivity for Type 2 Diabetes.',
          },
        },
        {
          id: 'm8',
          mealType: 'Lunch',
          recipeTitle: 'Swaahara Compatible Botanical Pad Thai',
          prepTime: '20 mins',
          verdict: 'safe',
          highlights: ['Coconut Aminos Base', 'Pumpkin Seeds', 'GL: 7'],
          recipe: {
            id: 'rec-8',
            title: 'Swaahara Botanical Pad Thai',
            servings: 1,
            prepTime: '20 mins',
            ingredients: ['Kelp Noodle Blend', 'Organic Coconut Aminos', 'Toasted Pumpkin Seeds', 'Monk Fruit Extract', 'Pasture Egg', 'Fresh Sprouts'],
            instructions: [
              'Wok sauté kelp noodles with coconut aminos and monk fruit extract.',
              'Scramble egg and toss with sprouts and toasted pumpkin seed garnish.',
            ],
            compatibilityNotes: 'Directly converted from restaurant risk dish into 100% profile-safe recipe.',
          },
        },
        {
          id: 'm9',
          mealType: 'Dinner',
          recipeTitle: 'Herb-Crusted Baked Trout with Steamed Broccolini',
          prepTime: '20 mins',
          verdict: 'safe',
          highlights: ['GL: 3', 'Low Sodium', 'Rich EPA/DHA'],
          recipe: {
            id: 'rec-9',
            title: 'Herb-Crusted Baked Trout',
            servings: 2,
            prepTime: '20 mins',
            ingredients: ['2 Fresh Trout Fillets', 'Fresh Parsley, Dill & Chives', '1 tbsp Olive Oil', 'Steamed Broccolini'],
            instructions: [
              'Coat trout fillets with minced fresh herbs and olive oil.',
              'Bake at 375°F (190°C) for 12 minutes. Serve with broccolini.',
            ],
            compatibilityNotes: 'Trout provides ultra-fresh protein with low histamine risk.',
          },
        },
      ],
    },
    {
      day: 'Thursday',
      dateLabel: 'Oct 15',
      meals: [
        {
          id: 'm10',
          mealType: 'Breakfast',
          recipeTitle: 'Coconut Yogurt Parfait with Seed Granola & Raspberries',
          prepTime: '8 mins',
          verdict: 'safe',
          highlights: ['Probiotic', 'GL: 4', 'Zero Dairy'],
          recipe: {
            id: 'rec-10',
            title: 'Coconut Parfait with Seed Granola',
            servings: 1,
            prepTime: '8 mins',
            ingredients: ['3/4 cup Unsweetened Coconut Yogurt', '2 tbsp Sunflower & Pumpkin Seed Granola', '1/3 cup Fresh Raspberries'],
            instructions: ['Layer coconut yogurt, seed granola, and raspberries in a bowl.'],
            compatibilityNotes: 'Probiotic support without dairy lactose or aged histamine enzymes.',
          },
        },
        {
          id: 'm11',
          mealType: 'Lunch',
          recipeTitle: 'Wild Halibut Fillet over Steamed Bok Choy',
          prepTime: '18 mins',
          verdict: 'safe',
          highlights: ['GL: 2', 'Sodium: 190mg', 'Pure Botanical'],
          recipe: {
            id: 'rec-11',
            title: 'Wild Halibut & Bok Choy',
            servings: 1,
            prepTime: '18 mins',
            ingredients: ['6 oz Wild Halibut Fillet', '2 heads Baby Bok Choy', '1 tbsp Coconut Aminos', 'Fresh Ginger & Garlic'],
            instructions: ['Steam halibut and bok choy over ginger-infused water for 10 minutes.'],
            compatibilityNotes: 'Clean steamed preparation meeting all renal and metabolic criteria.',
          },
        },
        {
          id: 'm12',
          mealType: 'Dinner',
          recipeTitle: 'Pasture Turkey & Zucchini Meatballs with Fresh Tomato Basil Reduction',
          prepTime: '30 mins',
          verdict: 'safe',
          highlights: ['Non-Aged Meat', 'GL: 5', 'Heart Safe'],
          recipe: {
            id: 'rec-12',
            title: 'Pasture Turkey & Zucchini Meatballs',
            servings: 3,
            prepTime: '30 mins',
            ingredients: ['1 lb Ground Pasture Turkey (Fresh)', '1 cup Shredded Zucchini', '1 Pasture Egg', 'Fresh Basil Sauce'],
            instructions: ['Mix turkey, zucchini, and egg. Form into meatballs and bake for 20 minutes at 400°F.'],
            compatibilityNotes: 'Zucchini adds moisture without breadcrumbs, keeping carb count minimal.',
          },
        },
      ],
    },
    {
      day: 'Friday',
      dateLabel: 'Oct 16',
      meals: [
        {
          id: 'm13',
          mealType: 'Breakfast',
          recipeTitle: 'Green Botanical Smoothie (Spinach, Cucumber, Coconut Water)',
          prepTime: '5 mins',
          verdict: 'safe',
          highlights: ['Hydration', 'GL: 2', 'Electrolytes'],
          recipe: {
            id: 'rec-13',
            title: 'Green Botanical Hydration Smoothie',
            servings: 1,
            prepTime: '5 mins',
            ingredients: ['1 cup Fresh Baby Spinach', '1/2 Cucumber', '1 cup Unsweetened Coconut Water', '1 tbsp Hemp Seeds'],
            instructions: ['Blend all ingredients until smooth.'],
            compatibilityNotes: 'Alkalizing and hydrating morning elixir with zero added sugar.',
          },
        },
        {
          id: 'm14',
          mealType: 'Lunch',
          recipeTitle: 'Warm Quinoa & Steamed Wild Salmon Salad',
          prepTime: '15 mins',
          verdict: 'safe',
          highlights: ['GL: 6', 'Omega-3', 'Low Sodium'],
          recipe: {
            id: 'rec-14',
            title: 'Quinoa & Wild Salmon Warm Salad',
            servings: 1,
            prepTime: '15 mins',
            ingredients: ['1/2 cup Cooked Quinoa', '5 oz Steamed Salmon', 'Mixed Baby Greens', 'Olive Oil & Lemon'],
            instructions: ['Toss warm quinoa and salmon over greens with olive oil dressing.'],
            compatibilityNotes: 'Sustained cellular energy without blood sugar spikes.',
          },
        },
        {
          id: 'm15',
          mealType: 'Dinner',
          recipeTitle: 'Roasted Duck Breast with Steamed Fennel & Pumpkin Puree',
          prepTime: '35 mins',
          verdict: 'safe',
          highlights: ['Histamine Level 1', 'GL: 5', 'Rich Mineral'],
          recipe: {
            id: 'rec-15',
            title: 'Roasted Duck Breast with Steamed Fennel',
            servings: 2,
            prepTime: '35 mins',
            ingredients: ['2 Fresh Duck Breasts', '2 heads Fennel, sliced', '1 cup Roasted Pumpkin Puree'],
            instructions: ['Score duck breast skin and pan-sear until crispy. Roast fennel with herbs.'],
            compatibilityNotes: 'Fresh duck provides rich healthy fats without histamine degradation.',
          },
        },
      ],
    },
    {
      day: 'Saturday',
      dateLabel: 'Oct 17',
      meals: [
        {
          id: 'm16',
          mealType: 'Breakfast',
          recipeTitle: 'Poached Pasture Eggs over Steamed Avocado & Asparagus Spears',
          prepTime: '10 mins',
          verdict: 'safe',
          highlights: ['GL: 2', 'Healthy Monounsaturated Fats', 'Sodium: 150mg'],
          recipe: {
            id: 'rec-16',
            title: 'Poached Eggs over Avocado & Asparagus',
            servings: 1,
            prepTime: '10 mins',
            ingredients: ['2 Organic Eggs', '1/2 Fresh Avocado', '6 Asparagus Spears', 'Chives & Olive Oil'],
            instructions: ['Poach eggs in simmering water for 3 minutes. Serve over sliced avocado and asparagus.'],
            compatibilityNotes: 'Healthy fats stabilize morning cortisol and glucose levels.',
          },
        },
        {
          id: 'm17',
          mealType: 'Lunch',
          recipeTitle: 'Steamed Halibut Bowl with Pumpkin Seed Pesto',
          prepTime: '20 mins',
          verdict: 'safe',
          highlights: ['Nut-Free', 'GL: 3', 'High Protein'],
          recipe: {
            id: 'rec-17',
            title: 'Steamed Halibut with Seed Pesto',
            servings: 1,
            prepTime: '20 mins',
            ingredients: ['6 oz Wild Halibut', '2 tbsp Nut-Free Pumpkin Seed Pesto', 'Steamed Zucchini'],
            instructions: ['Steam halibut for 8 minutes and spoon fresh pesto over top.'],
            compatibilityNotes: 'Clean, light weekend lunch engineered for maximum compatibility.',
          },
        },
        {
          id: 'm18',
          mealType: 'Dinner',
          recipeTitle: 'Wild Sea Bass en Papillote with Fresh Herbs & Summer Squash',
          prepTime: '25 mins',
          verdict: 'safe',
          highlights: ['Parchment Baked', 'GL: 3', 'Sodium: 170mg'],
          recipe: {
            id: 'rec-18',
            title: 'Wild Sea Bass en Papillote',
            servings: 2,
            prepTime: '25 mins',
            ingredients: ['2 Sea Bass Fillets', '1 Yellow Squash, sliced', 'Fresh Parsley, Dill & Olive Oil'],
            instructions: ['Seal fish and squash in parchment paper pouches. Bake at 380°F for 15 minutes.'],
            compatibilityNotes: 'Parchment baking preserves delicate fish oils and natural aromatic flavors.',
          },
        },
      ],
    },
    {
      day: 'Sunday',
      dateLabel: 'Oct 18',
      meals: [
        {
          id: 'm19',
          mealType: 'Breakfast',
          recipeTitle: 'Coconut Flour Pancakes with Fresh Strawberries & Monk Fruit Drizzle',
          prepTime: '15 mins',
          verdict: 'safe',
          highlights: ['Keto / Low Carb', 'GL: 5', 'Gluten-Free'],
          recipe: {
            id: 'rec-19',
            title: 'Coconut Flour Low-GL Pancakes',
            servings: 2,
            prepTime: '15 mins',
            ingredients: ['1/3 cup Coconut Flour', '4 Pasture Eggs', '1/4 cup Coconut Milk', 'Monk fruit syrup'],
            instructions: ['Whisk ingredients into batter. Cook small silver-dollar pancakes in avocado oil.'],
            compatibilityNotes: 'Coconut flour provides high fiber without wheat gluten or high glycemic starch.',
          },
        },
        {
          id: 'm20',
          mealType: 'Lunch',
          recipeTitle: 'Pasture Chicken Broth Soup with Bok Choy & Zucchini Noodles',
          prepTime: '20 mins',
          verdict: 'safe',
          highlights: ['Soothe & Nourish', 'Low Histamine Broth', 'GL: 2'],
          recipe: {
            id: 'rec-20',
            title: 'Pasture Chicken & Zucchini Noodle Soup',
            servings: 2,
            prepTime: '20 mins',
            ingredients: ['4 cups Quick-Simmered Non-Aged Chicken Broth', '1 cup Shredded Chicken Breast', 'Zucchini noodles & Bok Choy'],
            instructions: ['Bring broth to simmer. Add chicken, bok choy, and zucchini noodles for 3 minutes.'],
            compatibilityNotes: 'Short 20-minute simmer broth prevents histamine buildup seen in 24-hr bone broths.',
          },
        },
        {
          id: 'm21',
          mealType: 'Dinner',
          recipeTitle: 'Roasted Wild Salmon with Rosemary Sweet Potato Puree (Small Portion)',
          prepTime: '30 mins',
          verdict: 'safe',
          highlights: ['GL: 9', 'Antioxidant Rich', 'Sodium: 220mg'],
          recipe: {
            id: 'rec-21',
            title: 'Roasted Salmon with Rosemary Sweet Potato',
            servings: 2,
            prepTime: '30 mins',
            ingredients: ['2 Wild Salmon Fillets', '1 small Sweet Potato, steamed and mashed', 'Fresh Rosemary & Olive Oil'],
            instructions: ['Roast salmon fillets at 400°F for 10 minutes. Serve alongside rosemary mashed sweet potato.'],
            compatibilityNotes: 'Controlled portion of sweet potato provides complex carbohydrates while staying under GL 10.',
          },
        },
      ],
    },
  ],
};

export const MOCK_PROFILE_COMPARISONS: Record<string, FoodProfileComparison> = {
  'truffle-risotto': {
    foodId: 'truffle-risotto',
    foodName: 'Truffle & Wild Mushroom Arborio Risotto',
    category: 'Italian Cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&q=80&w=800',
    description: 'Arborio rice cooked with wild porcini mushrooms, truffle infusion, and 24-month aged parmesan cheese.',
    profiles: [
      {
        userProfile: CURRENT_USER_PROFILE,
        verdict: 'caution',
        verdictSummary: 'Requires Portion Control & Cheese Omission',
        keyReason: 'Aged parmesan introduces histamines; arborio white rice has a medium Glycemic Load (GL 16).',
        tags: ['Histamine Trigger in Cheese', 'Glycemic Load 16'],
      },
      {
        userProfile: COMPARISON_PROFILES[1], // Marcus K. (Keto & Celiac)
        verdict: 'risk',
        verdictSummary: 'High Carbohydrate & Cross-Gluten Hazard',
        keyReason: 'White Arborio rice contains 48g net carbs (exceeds Keto threshold) and risk of cross-contamination in broth.',
        tags: ['Keto Non-Compliant (48g Carbs)', 'Gluten Trace Risk'],
      },
      {
        userProfile: COMPARISON_PROFILES[2], // Elena R. (Low FODMAP & Kidney Guard)
        verdict: 'safe',
        verdictSummary: 'Low FODMAP Certified & Renal Compliant',
        keyReason: 'Porcini mushrooms in controlled 30g portion are FODMAP safe; low potassium & sodium profile.',
        tags: ['Low FODMAP Certified', 'Kidney Safe Sodium (240mg)'],
      },
    ],
  },
  'pad-thai-classic': {
    foodId: 'pad-thai-classic',
    foodName: 'Artisanal Tamarind Pad Thai',
    category: 'Thai Wok Dish',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&q=80&w=800',
    description: 'Traditional wok rice noodles with fermented anchovy sauce, palm sugar reduction, and crushed peanuts.',
    profiles: [
      {
        userProfile: CURRENT_USER_PROFILE,
        verdict: 'risk',
        verdictSummary: 'Severe Histamine & Allergen Hazard',
        keyReason: 'Fermented fish sauce triggers histamine response; crushed peanuts present direct allergen hazard.',
        tags: ['Tree Nut / Peanut Trigger', 'High Histamine Anchovy', 'Sodium 890mg'],
      },
      {
        userProfile: COMPARISON_PROFILES[1], // Marcus K.
        verdict: 'risk',
        verdictSummary: 'High Carb Rice Noodles & Peanut Protein',
        keyReason: 'Rice noodles and palm sugar break ketosis instantly; high glycemic spike.',
        tags: ['High Carb (62g)', 'Non-Keto Palm Sugar'],
      },
      {
        userProfile: COMPARISON_PROFILES[2], // Elena R.
        verdict: 'risk',
        verdictSummary: 'Soy & Peanut Allergen Trigger',
        keyReason: 'Contains peanuts and soy sauce triggers for IBS / Peanut sensitivity.',
        tags: ['Peanut Allergen', 'Soy Allergen', 'High Sodium'],
      },
    ],
  },
};
